import Foundation

struct Localization {
    var stats: Stats
    var uiElements: UIElements
    var kartParts: [String: String]

    struct Stats {
        var landSpeed: String
        var waterSpeed: String
        var airSpeed: String
        var antigravSpeed: String
        var accel: String
        var weight: String
        var landHandling: String
        var waterHandling: String
        var airHandling: String
        var antigravHandling: String
        var traction: String
        var miniTurbo: String
        var invuln: String
    }

    struct UIElements {
        var options: String
        var close: String
        var saveOptions: String
        var go: String
        var saveFilters: String
        var loadFilters: String
        var dontOptimize: String
        var minimize: String
        var maximize: String
        var bytes: String
        var kb: String
        var mb: String
        var maximumCache: String
        var saveImages: String
        var lowCacheSizeWarning: String
        var statsPlaceholder: String
        var resultsTruncatedWarning: String
        var character: String
        var kart: String
        var wheel: String
        var glider: String
        var limitCharacters: String
        var limitKarts: String
        var limitWheels: String
        var limitGliders: String
    }
}

let localizations: [Locale: Localization] = [
    Locale(identifier: "en_US"): Localization(
        stats: .init(
            landSpeed: "Ground speed",
            waterSpeed: "Water speed",
            airSpeed: "Glider speed",
            antigravSpeed: "Antigravity speed",
            accel: "Acceleration",
            weight: "Weight",
            landHandling: "Ground handling",
            waterHandling: "Water handling",
            airHandling: "Glider handling",
            antigravHandling: "Antigravity handling",
            traction: "Traction",
            miniTurbo: "Mini-Turbo",
            invuln: "Invincibility"
        ),
        uiElements: .init(
            options: "Options",
            close: "Close",
            saveOptions: "Save",
            go: "Go!",
            saveFilters: "Save these filters",
            loadFilters: "Load filters",
            dontOptimize: "Don't Optimize",
            minimize: "Minimize",
            maximize: "Maximize",
            bytes: "Bytes",
            kb: "kB",
            mb: "MB",
            maximumCache: "Maximum in-memory image cache size",
            saveImages: "Save images to disk",
            lowCacheSizeWarning:
                "Warning: reducing the image cache size too much will result in extraneous network requests and will not necessarily improve memory usage.",
            statsPlaceholder: "Select a combination to see its stats here!",
            resultsTruncatedWarning: "Results have been truncated for performance reasons.",
            character: "Character",
            kart: "Kart",
            wheel: "Tires",
            glider: "Glider",
            limitCharacters: "Limit characters",
            limitKarts: "Limit karts",
            limitWheels: "Limit tires",
            limitGliders: "Limit gliders"
        ),
        kartParts: [
            "Mario": "Mario",
            "Ludwig": "Ludwig",
            "MediumMii": "Mii (medium)",
            "Luigi": "Luigi",
            "Kamek": "Kamek",
            "Iggy": "Iggy",
            "Peach": "Peach",
            "Daisy": "Daisy",
            "Birdo": "Birdo",
            "Yoshi": "Yoshi",
            "Peachette": "Peachette",
            "Rosalina": "Rosalina",
            "KingBoo": "King Boo",
            "Link": "Link",
            "Pauline": "Pauline",
            "TanookiMario": "Tanooki Mario",
            "InklingBoy": "Inkling Boy",
            "VillagerBoy": "Villager (male)",
            "CatPeach": "Cat Peach",
            "InklingGirl": "Inkling Girl",
            "VillagerGirl": "Villager (female)",
            "DiddyKong": "Diddy Kong",
            "Toad": "Toad",
            "ShyGuy": "Shy Guy",
            "Larry": "Larry",
            "KoopaTroopa": "Koopa Troopa",
            "Lakitu": "Lakitu",
            "BowserJr": "Bowser Jr.",
            "Toadette": "Toadette",
            "Wendy": "Wendy",
            "Isabelle": "Isabelle",
            "PeteyPiranha": "Petey Piranha",
            "BabyMario": "Baby Mario",
            "BabyLuigi": "Baby Luigi",
            "DryBones": "Dry Bones",
            "LightMii": "Mii (light)",
            "BabyPeach": "Baby Peach",
            "BabyDaisy": "Baby Daisy",
            "BabyRosalina": "Baby Rosalina",
            "Lemmy": "Lemmy",
            "MetalMario": "Metal Mario",
            "PinkGoldPeach": "Pink Gold Peach",
            "Wiggler": "Wiggler",
            "Waluigi": "Waluigi",
            "DonkeyKong": "Donkey Kong",
            "Roy": "Roy",
            "Wario": "Wario",
            "DryBowser": "Dry Bowser",
            "FunkyKong": "Funky Kong",
            "HeavyMii": "Mii (heavy)",
            "Bowser": "Bowser",
            "Morton": "Morton",
            "StandardKart": "Standard Kart",
            "TheDuke": "The Duke",
            "PipeFrame": "Pipe Frame",
            "Mach8": "Mach 8",
            "SportsCoupe": "Sports Coupe",
            "SteelDriver": "Steel Driver",
            "TriSpeeder": "Tri-Speeder",
            "CatCruiser": "Cat Cruiser",
            "CircuitSpecial": "Circuit Special",
            "BDasher": "B Dasher",
            "PWing": "P-Wing",
            "Badwagon": "Badwagon",
            "GLA": "GLA",
            "Prancer": "Prancer",
            "Biddybuggy": "Biddybuggy",
            "MrScooty": "Mr. Scooty",
            "Landship": "Landship",
            "Sneeker": "Sneeker",
            "GoldStandard": "Gold Standard",
            "W25SilverArrow": "W 25 Silver Arrow",
            "StandardBike": "Standard Bike",
            "FlameRider": "Flame Rider",
            "WildWiggler": "Wild Wiggler",
            "300SLRoadster": "300 SL Roadster",
            "BlueFalcon": "Blue Falcon",
            "TanookiKart": "Tanooki Kart",
            "Streetle": "Streetle",
            "KoopaClown": "Koopa Clown",
            "MasterCycleZero": "Master Cycle Zero",
            "Comet": "Comet",
            "SportBike": "Sport Bike",
            "JetBike": "Jet Bike",
            "Varmint": "Varmint",
            "CityTripper": "City Tripper",
            "YoshiBike": "Yoshi Bike",
            "MasterCycle": "Master Cycle",
            "StandardATV": "Standard ATV",
            "TeddyBuggy": "Teddy Buggy",
            "BoneRattler": "Bone Rattler",
            "SplatBuggy": "Splat Buggy",
            "Inkstriker": "Inkstriker",
            "Standard": "Standard",
            "BlueStandard": "Blue Standard",
            "Monster": "Monster",
            "HotMonster": "Hot Monster",
            "Roller": "Roller",
            "AzureRoller": "Azure Roller",
            "Slim": "Slim",
            "Wood": "Wood",
            "CrimsonSlim": "Crimson Slim",
            "Slick": "Slick",
            "CyberSlick": "Cyber Slick",
            "Metal": "Metal",
            "Button": "Button",
            "LeafTires": "Leaf Tires",
            "OffRoad": "Off-Road",
            "RetroOffRoad": "Retro Off-Road",
            "TriforceTires": "Triforce Tires",
            "Sponge": "Sponge",
            "Cushion": "Cushion",
            "GoldTires": "Gold Tires",
            "GLATires": "GLA Tires",
            "AncientTires": "Ancient Tires",
            "SuperGlider": "Super Glider",
            "WaddleWing": "Waddle Wing",
            "HylianKite": "Hylian Kite",
            "CloudGlider": "Cloud Glider",
            "Parachute": "Parachute",
            "FlowerGlider": "Flower Glider",
            "PaperGlider": "Paper Glider",
            "WarioWing": "Wario Wing",
            "PlaneGlider": "Plane Glider",
            "GoldGlider": "Gold Glider",
            "Paraglider": "Paraglider",
            "PeachParasol": "Peach Parasol",
            "Parafoil": "Parafoil",
            "BowserKite": "Bowser Kite",
            "MKTVParafoil": "MKTV Parafoil",
        ]
    ),
    Locale(identifier: "en_GB"): Localization(
        stats: .init(
            landSpeed: "Ground speed",
            waterSpeed: "Water speed",
            airSpeed: "Glider speed",
            antigravSpeed: "Antigravity speed",
            accel: "Acceleration",
            weight: "Weight",
            landHandling: "Ground handling",
            waterHandling: "Water handling",
            airHandling: "Glider handling",
            antigravHandling: "Antigravity handling",
            traction: "Grip",
            miniTurbo: "Mini-Turbo",
            invuln: "Invincibility"
        ),
        uiElements: .init(
            options: "Options",
            close: "Close",
            saveOptions: "Save",
            go: "Go!",
            saveFilters: "Save these filters",
            loadFilters: "Load filters",
            dontOptimize: "Don't Optimise",
            minimize: "Minimise",
            maximize: "Maximise",
            bytes: "Bytes",
            kb: "kB",
            mb: "MB",
            maximumCache: "Maximum in-memory image cache size",
            saveImages: "Save images to disk",
            lowCacheSizeWarning:
                "Warning: reducing the image cache size too much will result in extraneous network requests and will not necessarily improve memory usage.",
            statsPlaceholder: "Select a combination to see its stats here!",
            resultsTruncatedWarning: "Results have been truncated for performance reasons.",
            character: "Character",
            kart: "Kart",
            wheel: "Tyres",
            glider: "Glider",
            limitCharacters: "Limit characters",
            limitKarts: "Limit karts",
            limitWheels: "Limit tyres",
            limitGliders: "Limit gliders"
        ),
        kartParts: [
            "Mario": "Mario",
            "Ludwig": "Ludwig",
            "MediumMii": "Mii (medium)",
            "Luigi": "Luigi",
            "Kamek": "Kamek",
            "Iggy": "Iggy",
            "Peach": "Peach",
            "Daisy": "Daisy",
            "Birdo": "Birdo",
            "Yoshi": "Yoshi",
            "Peachette": "Peachette",
            "Rosalina": "Rosalina",
            "KingBoo": "King Boo",
            "Link": "Link",
            "Pauline": "Pauline",
            "TanookiMario": "Tanooki Mario",
            "InklingBoy": "Inkling Boy",
            "VillagerBoy": "Villager (male)",
            "CatPeach": "Cat Peach",
            "InklingGirl": "Inkling Girl",
            "VillagerGirl": "Villager (female)",
            "DiddyKong": "Diddy Kong",
            "Toad": "Toad",
            "ShyGuy": "Shy Guy",
            "Larry": "Larry",
            "KoopaTroopa": "Koopa Troopa",
            "Lakitu": "Lakitu",
            "BowserJr": "Bowser Jr.",
            "Toadette": "Toadette",
            "Wendy": "Wendy",
            "Isabelle": "Isabelle",
            "PeteyPiranha": "Petey Piranha",
            "BabyMario": "Baby Mario",
            "BabyLuigi": "Baby Luigi",
            "DryBones": "Dry Bones",
            "LightMii": "Mii (light)",
            "BabyPeach": "Baby Peach",
            "BabyDaisy": "Baby Daisy",
            "BabyRosalina": "Baby Rosalina",
            "Lemmy": "Lemmy",
            "MetalMario": "Metal Mario",
            "PinkGoldPeach": "Pink Gold Peach",
            "Wiggler": "Wiggler",
            "Waluigi": "Waluigi",
            "DonkeyKong": "Donkey Kong",
            "Roy": "Roy",
            "Wario": "Wario",
            "DryBowser": "Dry Bowser",
            "FunkyKong": "Funky Kong",
            "HeavyMii": "Mii (heavy)",
            "Bowser": "Bowser",
            "Morton": "Morton",
            "StandardKart": "Standard Kart",
            "TheDuke": "The Duke",
            "PipeFrame": "Pipe Frame",
            "Mach8": "Mach 8",
            "SportsCoupe": "Sports Coupé",
            "SteelDriver": "Steel Driver",
            "TriSpeeder": "Tri-Speeder",
            "CatCruiser": "Cat Cruiser",
            "CircuitSpecial": "Circuit Special",
            "BDasher": "B Dasher",
            "PWing": "P-Wing",
            "Badwagon": "Badwagon",
            "GLA": "GLA",
            "Prancer": "Prancer",
            "Biddybuggy": "Buggybud",
            "MrScooty": "Mr Scooty",
            "Landship": "Landship",
            "Sneeker": "Bounder",
            "GoldStandard": "Gold Standard",
            "W25SilverArrow": "W 25 Silver Arrow",
            "StandardBike": "Standard Bike",
            "FlameRider": "Flame Rider",
            "WildWiggler": "Wild Wiggler",
            "300SLRoadster": "300 SL Roadster",
            "BlueFalcon": "Blue Falcon",
            "TanookiKart": "Tanooki Kart",
            "Streetle": "Streetle",
            "KoopaClown": "Koopa Clown",
            "MasterCycleZero": "Master Cycle Zero",
            "Comet": "Comet",
            "SportBike": "Sport Bike",
            "JetBike": "Jet Bike",
            "Varmint": "Varmint",
            "CityTripper": "City Tripper",
            "YoshiBike": "Yoshi Bike",
            "MasterCycle": "Master Cycle",
            "StandardATV": "Standard Quad",
            "TeddyBuggy": "Teddy Buggy",
            "BoneRattler": "Bone Rattler",
            "SplatBuggy": "Splat Buggy",
            "Inkstriker": "Inkstriker",
            "Standard": "Normal",
            "BlueStandard": "Normal Blue",
            "Monster": "Monster",
            "HotMonster": "Funky Monster",
            "Roller": "Roller",
            "AzureRoller": "Azure Roller",
            "Slim": "Slim",
            "Wood": "Wooden",
            "CrimsonSlim": "Crimson Slim",
            "Slick": "Slick",
            "CyberSlick": "Cyber Slick",
            "Metal": "Metal",
            "Button": "Button",
            "LeafTires": "Leaf Tyres",
            "OffRoad": "Off-Road",
            "RetroOffRoad": "Retro Off-Road",
            "TriforceTires": "Triforce Tyres",
            "Sponge": "Sponge",
            "Cushion": "Cushion",
            "GoldTires": "Gold Wheels",
            "GLATires": "GLA Wheels",
            "AncientTires": "Ancient Tyres",
            "SuperGlider": "Super Glider",
            "WaddleWing": "Waddle Wing",
            "HylianKite": "Hylian Kite",
            "CloudGlider": "Cloud Glider",
            "Parachute": "Parachute",
            "FlowerGlider": "Flower Glider",
            "PaperGlider": "Paper Glider",
            "WarioWing": "Wario Wing",
            "PlaneGlider": "Plane Glider",
            "GoldGlider": "Gold Glider",
            "Paraglider": "Paraglider",
            "PeachParasol": "Peach Parasol",
            "Parafoil": "Parafoil",
            "BowserKite": "Bowser Kite",
            "MKTVParafoil": "MKTV Parafoil",
        ]
    ),
]
